### PR TITLE
Enable phpspec with Symfony 6

### PR DESCRIPTION
**Pull request by kbond**
Currently blocked by:

- [x] https://github.com/phpspec/prophecy/issues/527

### CODE REVIEW

**Comment by kbond** [comment]
I believe if you re-run these actions, it will pass.

**Comment by umpirsky** [comment]
Strangely enough I don't have option to rerun.

**Comment by kbond** [comment]
phpspec's now at least running but I'm not familiar enough with the tool to fix the failures.

**Comment by umpirsky** [comment]
The problem is that `bin/tools/phpspec/vendor/symfony/service-contracts/ServiceSubscriberInterface.php` and `vendor/symfony/framework-bundle/Routing/Router.php` are not compatible.

It's probably incompatibility between `symfony/service-contracts` and `symfony/framework-bundle` package versions.

```
PHP Fatal error:  Declaration of Symfony\Bundle\FrameworkBundle\Routing\Router::getSubscribedServices() must be compatible with Symfony\Contracts\Service\ServiceSubscriberInterface::getSubscribedServices(): array in /home/runner/work/UmpirskyI18nRoutingBundle/UmpirskyI18nRoutingBundle/vendor/symfony/framework-bundle/Routing/Router.php on line 202
```

**Comment by umpirsky** [comment]
It's better in https://github.com/kbond/UmpirskyI18nRoutingBundle/pull/1, but still have:

```
/bin/tools/phpspec/vendor/bin/phpspec ru      
Umpirsky/I18nRoutingBundle/Routing/Strategy/PrefixExceptDefaultStrategy           
  21  - it generates route collection one as is and one with locale prefixed route
      exception [err:TypeError("Double\Symfony\Component\Routing\Route\P3::getPath(): Return value must be of type string, null returned")] has been thrown.

Umpirsky/I18nRoutingBundle/Routing/Strategy/PrefixStrategy                      
  21  - it generates route collection with locale prefixed route
      exception [err:TypeError("Double\Symfony\Component\Routing\Route\P3::getPath(): Return value must be of type string, null returned")] has been thrown.

                         66%                                     33%             6
5 specs
6 examples (4 passed, 2 broken)
29ms
```

**Comment by umpirsky** [comment]
It highly depends on the version, so it's hard to cover all cases.

**Pull request closed without merging**
