### PR TITLE
Allow Symfony 6

### PR DESCRIPTION
**Pull request by kbond**

### CODE REVIEW

**Comment by kbond** [comment]
https://github.com/phpspec/prophecy/issues/527 is the remaining blocker. My suggestion would be another job outside the matrix that runs just phpspec on 7.4. WDYT?

**Review by umpirsky — APPROVED** [review]
Thanks!

**Comment by umpirsky** [comment]
CI is [failing](https://github.com/umpirsky/UmpirskyI18nRoutingBundle/runs/4080406136?check_suite_focus=true).

**Comment by umpirsky** [comment]
If you don't have time to wait for https://github.com/phpspec/prophecy/issues/527 to be resolved, we can do that and create issue to update once https://github.com/phpspec/prophecy/issues/527 is fixed.

**Comment by kbond** [comment]
Is it important to run phpspec on every matrix environment? I'm not familiar with this library.

We sort of have 2 options:
1. Move the phpspec test to it's own job running in a compatible environment
2. Disable phpspec for this PR, when merged, I'll open another PR to re-add where we can wait on phpspec/prophecy#527

**Comment by umpirsky** [comment]
We can do 2. It's desirable to run it on every matrix if possible. Thanks.

**Comment by kbond** [comment]
Ok, this is ready. I disabled phpspec on Symfony 6 only.

**Comment by kbond** [comment]
@umpirsky, could I trouble you for a new tag?

**Comment by umpirsky** [comment]
Done https://github.com/umpirsky/UmpirskyI18nRoutingBundle/releases/tag/0.0.6

**Pull request merged**
